file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/pc/.gitconfig	user.email=98012299+TechisHeaven@users.noreply.github.com
file:C:/Users/pc/.gitconfig	user.name=Himanshu verma
file:C:/Users/pc/.gitconfig	user.username=TechisHeaven
file:C:/Users/pc/.gitconfig	safe.directory=F:/Web development stuff/React Chat app
file:C:/Users/pc/.gitconfig	safe.directory=*
file:C:/Users/pc/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/pc/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/pc/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/pc/.gitconfig	filter.lfs.required=true
file:C:/Users/pc/.gitconfig	init.defaultbranch=main
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/Akshay7311/onlineshopping.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
